
namespace :ci do

  namespace :test do

    desc <<-EOS
A quick acceptance test, named because it has no pre-suites to run
EOS
    task :quick do

    sh("beaker",
       "--hosts", ENV['CONFIG'] || "config/nodes/redhat-7-x86_64.yaml",
       "--tests", "tests",
       "--log-level", "debug",
       "--keyfile", ENV['KEY'] || "#{ENV['HOME']}/.ssh/id_rsa")
    end

  end

end

task :default => 'ci:test:quick'